"""HTML email template for digest."""

from datetime import date
from html import escape
from typing import Any, List, Tuple
from urllib.parse import urlparse

from langchain_core.documents import Document

from paperfind.documents import extract_title_and_abstract

# Type alias for recommendation tuple: (doi, (score, doc, zotero_title))
Recommendation = Tuple[str, Tuple[float, Document, str]]


def _get_doi_link(doi: str) -> str:
    """Convert DOI to clickable URL."""
    if not doi:
        return ""
    if doi.startswith("arxiv:"):
        arxiv_id = doi.replace("arxiv:", "")
        return f"https://arxiv.org/abs/{arxiv_id}"
    return f"https://doi.org/{doi}"


def _is_valid_url(url: str) -> bool:
    """Return True if the URL is http(s) and has a network location."""
    if not url:
        return False
    parsed = urlparse(url)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def render_digest(
    recommendations: List[Recommendation],
    digest_date: date,
    rerank: bool = True,
) -> str:
    """
    Render recommendations as an HTML email.

    Args:
        recommendations: List of (doi, (score, doc, zotero_title)) tuples
        digest_date: Date of the digest
        rerank: If True, scores are rerank scores (not vector similarity)

    Returns:
        HTML string
    """
    papers_html = []

    for rank, (doi, (score, doc, zotero_title)) in enumerate(recommendations, 1):
        title, abstract = extract_title_and_abstract(doc)
        authors = doc.metadata.get("authors", "Unknown")
        source = doc.metadata.get("source", "")
        pub_date = doc.metadata.get("created_date", "")

        # Get abstract (truncate for email)
        abstract_display = ""
        if abstract:
            abstract_display = " ".join(abstract.split())
            if len(abstract_display) > 300:
                abstract_display = abstract_display[:300] + "..."

        doi_link = _get_doi_link(doi)
        if not _is_valid_url(doi_link):
            doi_link = ""
        if rerank:
            score_line = f"Rerank score {score:.4f}"
        else:
            similarity = 1 / (1 + score)
            score_line = f"{similarity:.0%} similar"

        title_display = escape(title)
        authors_display = escape(authors)
        source_display = escape(source)
        abstract_display = escape(abstract_display)
        zotero_title_display = zotero_title or ""
        zotero_title_short = zotero_title_display[:50]
        zotero_title_short = escape(zotero_title_short)

        if doi_link:
            title_html = (
                f'<a href="{escape(doi_link, quote=True)}" '
                'style="color: #1a73e8; text-decoration: none;">'
                f"{title_display}</a>"
            )
        else:
            title_html = title_display

        paper_html = f"""
        <div style="margin-bottom: 24px; padding: 16px; background: #f8f9fa; border-radius: 8px; border-left: 4px solid #4285f4;">
            <div style="font-size: 12px; color: #5f6368; margin-bottom: 8px;">
                #{rank} &bull; {score_line} &bull; similar to <em>{zotero_title_short}{'...' if len(zotero_title_display) > 50 else ''}</em>
            </div>
            <div style="font-size: 16px; font-weight: 600; color: #202124; margin-bottom: 8px;">
                {title_html}
            </div>
            <div style="font-size: 13px; color: #5f6368; margin-bottom: 8px;">
                {authors_display}
            </div>
            <div style="font-size: 12px; color: #80868b; margin-bottom: 8px;">
                {pub_date} &bull; {source_display}
            </div>
            <div style="font-size: 14px; color: #3c4043; line-height: 1.5;">
                {abstract_display}
            </div>
        </div>
        """
        papers_html.append(paper_html)

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #ffffff;">
    <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="font-size: 24px; color: #202124; margin: 0;">Paper Recommendations</h1>
        <p style="font-size: 14px; color: #5f6368; margin: 8px 0 0 0;">{digest_date.strftime('%B %d, %Y')}</p>
    </div>

    <div style="margin-bottom: 24px;">
        <p style="font-size: 14px; color: #3c4043; line-height: 1.6;">
            Here are today's top {len(recommendations)} paper recommendations based on your Zotero library.
        </p>
    </div>

    {''.join(papers_html)}

    <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e8eaed; text-align: center;">
        <p style="font-size: 12px; color: #80868b;">
            Generated by <a href="https://github.com/liuyq123/paperfind" style="color: #1a73e8;">Paperfind</a>
        </p>
    </div>
</body>
</html>
    """

    return html
